function test_PlotResultsLargeSamples_new(GenericExpFolderName,ProjectName)
% test_PlotResultsLargeSamples_new plots the empirical errors of the tested 
% algorithms as a function of the Hamming distance. This function is used
% when plotting results for larger point sets.
%
% See also test_PlotResults_new

% Loading Results
PathName=[GenericExpFolderName '/REPORT'];
FileName=fullfile(PathName,[ProjectName '.def']);
data=bb_cl_loadparam(FileName);

N=0:(length(data.EmpiricalError_SubOptimalPseed)-1);
LineWidthValue=1;

figure;
plot(N,data.EmpiricalError_SubOptimalPseed,'-+','LineWidth',LineWidthValue,'Color',[0.1 0.8 0.9]);
hold on;
plot(N,data.EmpiricalError_FCM*ones(size(N)),'g-s','LineWidth',LineWidthValue);
plot(N,data.EmpiricalError_KM*ones(size(N)),'b-v','LineWidth',LineWidthValue);
plot(N,data.EmpiricalError_HieSi*ones(size(N)),'k-*','LineWidth',LineWidthValue);
plot(N,data.EmpiricalError_HieCo*ones(size(N)),'c-^','LineWidth',LineWidthValue);
plot(N,data.EmpiricalError_FCM_OPS*ones(size(N)),'-<','LineWidth',LineWidthValue,'Color',[0.1 0.5 0.5]);
plot(N,data.EmpiricalError_KP*ones(size(N)),'m->','LineWidth',LineWidthValue);
plot(N,data.EmpiricalError_Random*ones(size(N)),'-.','LineWidth',LineWidthValue,'Color',[0.2 0.8 0.5]);
try
    plot(N,data.EmpiricalError_Classifier_*ones(size(N)),'-p','LineWidth',LineWidthValue,'Color',[0.1 0.5 0.8]);
    legend('Subopt. Pseed','FCM','K-Means','Hier. (Si)','Hier. (Co)','FCM-OCS','K-POD','Random','Classifier');
    MaxError=max([data.EmpiricalError_SubOptimalPseed,...
        data.EmpiricalError_FCM,...
        data.EmpiricalError_KM,...
        data.EmpiricalError_HieSi,...
        data.EmpiricalError_HieCo,...
        data.EmpiricalError_FCM_OPS,...
        data.EmpiricalError_KP,...
        data.EmpiricalError_Random,...
        data.EmpiricalError_Classifier_]);
    
    MinError=min([data.EmpiricalError_SubOptimalPseed,...
        data.EmpiricalError_FCM,...
        data.EmpiricalError_KM,...
        data.EmpiricalError_HieSi,...
        data.EmpiricalError_HieCo,...
        data.EmpiricalError_FCM_OPS,...
        data.EmpiricalError_KP,...
        data.EmpiricalError_Random,...
        data.EmpiricalError_Classifier_]);
catch
    legend('Subopt. Pseed','FCM','K-Means','Hier. (Si)','Hier. (Co)','FCM-OCS','K-POD','Random');
    MaxError=max([data.EmpiricalError_SubOptimalPseed,...
        data.EmpiricalError_FCM,...
        data.EmpiricalError_KM,...
        data.EmpiricalError_HieSi,...
        data.EmpiricalError_HieCo,...
        data.EmpiricalError_FCM_OPS,...
        data.EmpiricalError_KP,...
        data.EmpiricalError_Random]);
    
    MinError=min([data.EmpiricalError_SubOptimalPseed,...
        data.EmpiricalError_FCM,...
        data.EmpiricalError_KM,...
        data.EmpiricalError_HieSi,...
        data.EmpiricalError_HieCo,...
        data.EmpiricalError_FCM_OPS,...
        data.EmpiricalError_KP,...
        data.EmpiricalError_Random]);
end
hold off;
xlabel('Hamming Distance');
ylabel('Empirical Error [%]');
ylim([MinError-5 MaxError+5]);
set(gca,'XTick',N);
set(findall(gcf,'Type','text'),'FontSize',14);

% Saving Files
PathName=[GenericExpFolderName '/GRAPHICS'];
mkdir(PathName);
FileName=fullfile(PathName,ProjectName);
saveas(gcf,[FileName 'COLOR'],'jpeg');
saveas(gcf,[FileName 'COLOR'],'epsc2');
saveas(gcf,[FileName 'GREY'],'eps');
return